#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# shellcheck shell=bash disable=SC1091,SC2039,SC2166
#
#  PKGFILE
#  Created: sáb 03 jan 2026 00:32:47 -04
#  Altered: sáb 03 jan 2026 00:32:47 -04
#  Updated: sáb 03 jan 2026 00:32:47 -04
#
#  Copyright (c) 2019-2026, Vilmar Catafesta <vcatafesta@gmail.com>
#  Copyright (c) 2025-2026, VoidLinuxBR Team
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
# Maintainer: Vilmar Catafesta <vcatafesta@gmail.com>

pkgname=voidbr-pkgname
pkgdesc="Package template for VoidLinuxBR"
pkgver=$(date +%Y%m%d)
pkgrel=$(date +%H%M)
arch=('any')
license=('MIT')
#url="ssh://git@github.com/voidlinuxbr/${pkgname}"
url="https://github.com/voidlinuxbr/${pkgname}"
source=("git+${url}.git")
md5sums=('SKIP')
makedepends=()
depends=()

# Automatically detect and use the correct install file
if [ -e "${pkgname}.install" ]; then
	install=${pkgname}.install
elif [ -e "pkgbuild.install" ]; then
	install=pkgfile.install
fi

package() {
	# Verify default folder
	if [ -d "${srcdir}/${pkgname}/${pkgname}" ]; then
		InternalDir="${srcdir}/${pkgname}/${pkgname}"
	else
		InternalDir="${srcdir}/${pkgname}"
	fi

	cd "${srcdir}/${pkgname}"
	# Copiar a estrutura de /etc, /usr e /opt para /
	local dirs=("boot" "etc" "opt" "usr")
	for dir in "${dirs[@]}"; do
		if [ -d "${InternalDir}/${dir}" ]; then
			cp -a "${InternalDir}/${dir}" "${pkgdir}/"
		fi
	done

	# Install license file if present
	if [ -f "LICENSE" ]; then
		install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
	fi

	# Install documentation if present
	if [ -f "README.md" ]; then
		install -Dm644 README.md "${pkgdir}/usr/share/doc/${pkgname}/README.md"
	fi
}
